# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
 
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: publish
      run: dotnet publish --no-restore
    - name: publish
      run: dotnet publish --no-restore
      # path
    - name: tmux new
      run: tmux new -s ZstdNet
      
    - name: dotnet run
      run:  dotnet ZstdNet.dll
     # path

    - name: tmux kill-session
      run: tmux kill-session -t ZstdNet
      
    - name: tmux new
      run: tmux new -s ZstdNet
      
    - name: dotnet run
      run:  dotnet ZstdNet.dll
 

 
